backend:
  name: git-gateway
  branch: main

# (opsional tapi bagus)
site_url: https://gojimms.com
display_url: https://gojimms.com

# biar bisa jalan saat dev lokal
local_backend: true

media_folder: "assets/images/blog"
public_folder: "/assets/images/blog"

publish_mode: editorial_workflow

collections:
  - name: "posts_id"
    label: "Posts (ID)"
    folder: "content/posts/id"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Tags", name: "tags", widget: "list", default: ["IT"] }
      - { label: "Cover Image", name: "coverImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "posts_en"
    label: "Posts (EN)"
    folder: "content/posts/en"
    create: true
    slug: "{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Tags", name: "tags", widget: "list", default: ["IT"] }
      - { label: "Cover Image", name: "coverImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
